// Generated by CoffeeScript 1.8.0
(function() {
  var CoffeeBuzz;

  CoffeeBuzz = (function() {
    function CoffeeBuzz() {}

    CoffeeBuzz.prototype.divisibleByThree = function(number) {
      return this.divisibleBy(number, 3);
    };

    CoffeeBuzz.prototype.divisibleByFive = function(number) {
      return this.divisibleBy(number, 5);
    };

    CoffeeBuzz.prototype.divisibleByFifteen = function(number) {
      return this.divisibleBy(number, 15);
    };

    CoffeeBuzz.prototype.divisibleBy = function(number, divisor) {
      return number % divisor === 0;
    };

    CoffeeBuzz.prototype.prints = function(number) {
      if (this.divisibleByFifteen(number)) {
        return "coffeebuzz";
      }
      if (this.divisibleByFive(number)) {
        return "buzz";
      }
      if (this.divisibleByThree(number)) {
        return "fizz";
      } else {
        return number;
      }
    };

    return CoffeeBuzz;

  })();

  module.exports = CoffeeBuzz;

}).call(this);
